### ISSUE TITLE
SourceArn support

### ISSUE THREAD

**Issue by bsamartins** [loopingz/aws-smtp-relay#16]
Is there a possiblity of adding (optional) support for sourceArn when sending emails?

**Comment by loopingz** [comment]
Thanks to the contribution of @basschipper, you have now the possibility to use -a or --sourceArn options

**Comment by basschipper** [comment]
What a coincidence!

@bsamartins does this work for you? Cause I just found out that when the mail body contains a "from: xxx@xxx.xxx" header it still gives me a verification error, you probably also need to implement the FromArn.

**Comment by bsamartins** [comment]
@basschipper, sorry for the delay here.
Yes, I got the same issue. It only started working after adding the fromArn. 
sourceArn was actually not required (at least in our use case), but fromArn was 🙄 .
