### ISSUE TITLE
Issue in download the CVE definitions when building

### ISSUE THREAD

**Issue by vijaybisht2007** [loopingz/aws-smtp-relay#41]
## Expected behavior
Download the JSON lib from link ‘https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.json.gz

## Actual behavior
We are facing an issue in compiling the ‘aws-smtp-relay’ project as below screenshot. Compiler trying to download the JSON lib from link ‘https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2019.json.gz  but getting 404 error 

![Comp_Issue_aws_smtp_relay](https://user-images.githubusercontent.com/52530492/139619903-4d305b05-a79f-43b1-b03a-766ef0d87249.png)
## Steps to reproduce the behavior
Compile in fresh machine

**Comment by loopingz** [comment]
Required an update of the module: `dependency-check-maven`
