### ISSUE TITLE
From: header required in DATA command

### ISSUE THREAD

**Issue by morganchristiansson** [loopingz/aws-smtp-relay#6]
Getting this error when using an application e-mail alerts.

```Exception in thread "pool-1-thread-28330" com.amazonaws.services.simpleemail.model.AmazonSimpleEmailServiceException: Missing required header 'From'. (Service: AmazonSimpleEmailService; Status Code: 400; Error Code: InvalidParameterValue; Request ID: xxxxxx)```

The program sends from header like this.

```MAIL FROM:<from@domain.com>```

This is not accepted by aws ses which also requires a ```From: <from@domain.com>``` header in the e-mail or it rejects the API call with the above error.

Will be working to resolve this now.

**Comment by morganchristiansson** [comment]
Here's an example to test it:

```
telnet 172.17.0.4 10025 <<EOF
HELO mog.se
MAIL FROM: <from@domain.co>
RCPT TO: <to@domain.com>
DATA
From: <from@domain.com>
To: <from@domain.com>

Type any content that you want, press enter.
Then put a period (.) and then enter to exit
.
EOF
```

If the From: header is removed from the DATA body then we get the AmazonSimpleEmailServiceException above.

**Comment by loopingz** [comment]
I'm closing this issue at your last Pull request cover this one
